error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:17:18.790Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:18:11.225Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:19:17.739Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:21:43.386Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:22:48.678Z"}
error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Function.listen (E:\Bridgelabz\Backend\Fundoo-note\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\src\/index.js:37:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._compile (E:\Bridgelabz\Backend\Fundoo-note\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .js] (E:\Bridgelabz\Backend\Fundoo-note\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.runMain (node:internal/modules/run_main:83:12)
    at Object.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\node\src\_babel-node.ts:222:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {"date":"Thu Dec 14 2023 15:01:02 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":313.531},"process":{"argv":["node","E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\index.js"],"cwd":"E:\\Bridgelabz\\Backend\\Fundoo-note","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18735438,"external":21750913,"heapTotal":77709312,"heapUsed":46821264,"rss":115052544},"pid":10184,"uid":null,"version":"v20.9.0"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1872:16)\n    at listenInCluster (node:net:1920:12)\n    at Server.listen (node:net:2008:7)\n    at Function.listen (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\/index.js:37:5)\n    at Module._compile (node:internal/modules/cjs/loader:1241:14)\n    at Module._compile (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)\n    at Object.newLoader [as .js] (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1091:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:938:12)\n    at Function.runMain (node:internal/modules/run_main:83:12)\n    at Object.<anonymous> (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\node\\src\\_babel-node.ts:222:12)\n    at Module._compile (node:internal/modules/cjs/loader:1241:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)\n    at Module.load (node:internal/modules/cjs/loader:1091:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:938:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-12-14T09:31:02.822Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1872,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1920,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":2008,"method":"listen","native":false},{"column":24,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\/index.js","function":null,"line":37,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1241,"method":"_compile","native":false},{"column":24,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1295,"method":".js","native":false},{"column":7,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1091,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":938,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.runMain","line":83,"method":"runMain","native":false},{"column":12,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\node\\src\\_babel-node.ts","function":null,"line":222,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1241,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1295,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1091,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":938,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":83,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":23,"method":null,"native":false}]}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:32:50.480Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:33:53.106Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:34:16.851Z"}
error: 
    status - 500 
    message - ValidationError: User validation failed: firstName: Path `firstName` is required.
    at model.Document.invalidate (E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2786:32)
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\document.js:2578:17
    at E:\Bridgelabz\Backend\Fundoo-note\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:34:51.103Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:17:5)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.throw (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T09:40:31.667Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" length must be at least 4 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:34:21.297Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" is not allowed to be empty 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:34:55.391Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" length must be at least 2 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:35:15.964Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" length must be at least 2 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:35:30.235Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" length must be at least 2 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:35:33.140Z"}
error: 
    status - 500 
    message - ValidationError: "phone" length must be at least 10 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:35:50.302Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 6 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:35:59.289Z"}
error: 
    status - 500 
    message - Error: User with the same email already exists
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:14:9)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:41:51.477Z"}
error: 
    status - 500 
    message - Error: User with the same email already exists
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:14:9)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:43:36.510Z"}
error: 
    status - 500 
    message - Error: User with the same email already exists
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:14:9)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:43:38.489Z"}
error: 
    status - 500 
    message - Error: User with the same email already exists
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:14:8)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-12-14T10:44:06.992Z"}
error: uncaughtException: User with the same email already exists
Error: User with the same email already exists
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:16:13)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Thu Dec 14 2023 16:38:29 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":6160.234},"process":{"argv":["node","E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\index.js"],"cwd":"E:\\Bridgelabz\\Backend\\Fundoo-note","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18705768,"external":21721243,"heapTotal":81936384,"heapUsed":53493256,"rss":119435264},"pid":10852,"uid":null,"version":"v20.9.0"},"stack":"Error: User with the same email already exists\n    at _callee2$ (E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\services\\/user.service.js:16:13)\n    at tryCatch (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-12-14T11:08:29.522Z","trace":[{"column":13,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\services\\/user.service.js","function":"_callee2$","line":16,"method":null,"native":false},{"column":16,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":74,"method":"next","native":false},{"column":24,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":22,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: uncaughtException: User with the same email already exists
Error: User with the same email already exists
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:16:13)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Thu Dec 14 2023 16:39:00 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":6191.328},"process":{"argv":["node","E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\index.js"],"cwd":"E:\\Bridgelabz\\Backend\\Fundoo-note","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18263490,"external":21278965,"heapTotal":82800640,"heapUsed":48272984,"rss":119304192},"pid":268,"uid":null,"version":"v20.9.0"},"stack":"Error: User with the same email already exists\n    at _callee2$ (E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\services\\/user.service.js:16:13)\n    at tryCatch (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-12-14T11:09:00.610Z","trace":[{"column":13,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\services\\/user.service.js","function":"_callee2$","line":16,"method":null,"native":false},{"column":16,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":74,"method":"next","native":false},{"column":24,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":22,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: uncaughtException: User with the same email already exists
Error: User with the same email already exists
    at _callee2$ (E:\Bridgelabz\Backend\Fundoo-note\src\services\/user.service.js:15:13)
    at tryCatch (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\Bridgelabz\Backend\Fundoo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Thu Dec 14 2023 16:39:24 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":6215},"process":{"argv":["node","E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\index.js"],"cwd":"E:\\Bridgelabz\\Backend\\Fundoo-note","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18725878,"external":21741353,"heapTotal":82219008,"heapUsed":50825888,"rss":119037952},"pid":13676,"uid":null,"version":"v20.9.0"},"stack":"Error: User with the same email already exists\n    at _callee2$ (E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\services\\/user.service.js:15:13)\n    at tryCatch (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.next (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-12-14T11:09:24.290Z","trace":[{"column":13,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\src\\services\\/user.service.js","function":"_callee2$","line":15,"method":null,"native":false},{"column":16,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":74,"method":"next","native":false},{"column":24,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"E:\\Bridgelabz\\Backend\\Fundoo-note\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":22,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
